stages:
  - test
  - docker

variables:
  IMAGE_NAME: $CI_REGISTRY_IMAGE:latest
  DOCKER_TLS_CERTDIR: ''

test:
  stage: test
  image: golang:1.25.1-alpine
  script:
    - apk add --no-cache git bash
    - go mod download
    - go test -v ./...
  only:
    - gitlab-only-feature-v.1.1
    - merge_requests

docker-build:
  stage: docker
  image: docker:24.0.5
  services:
    - docker:24.0.5-dind
  variables:
    DOCKER_DRIVER: overlay2
  script:
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY
    - docker build -t $IMAGE_NAME .
    - docker push $IMAGE_NAME
  only:
    - gitlab-only-feature-v.1.1
